server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    username: postgres
    password: password
    driver-class-name: org.h2.Driver
  liquibase:
    change-log:classpath:db.changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl-auto: create-drop
        show-sql: true